DB_USER = 'SIMV'
DB_PASSWORD = 'TAcuato+-14'

# Parámetros de colores
BACKGROUND_COLOR = 'beige'
TITLE_COLOR = 'darkblue'
LINEEDIT_BACKGROUND_COLOR = 'beige'
LINEEDIT_TEXT_COLOR = 'black'
TEXT_COLOR = 'black'

CLEAR_BUTTON_DISABLED = False

SAVE_BUTTON_DISABLED = False
CLEAR_BUTTON_DISABLED = True

SAVE_BUTTON_DISABLED = True
