ICONOS = {
    'atras': 'iconos\atras.png',
    'ayuda': 'iconos\ayuda.png',
    'config': 'iconos\config.png',
    'consultas': 'iconos\consultas.png',
    'emergencia': 'iconos\emergencia.png',
    'examen': 'iconos\examen.png',
    'farmacia': 'iconos\farmacia.png',
    'ginecologia': 'iconos\ginecologia.png',
    'guardar': 'iconos\guardar.png',
    'hamburguesa': 'iconos\hamburguesa.png',
    'historial': 'iconos\historial.png',
    'ih2': 'iconos\ih2.png',
    'inicio': 'iconos\inicio.png',
    'inventario': 'iconos\inventario.png',
    'limpiar': 'iconos\limpiar.png',
    'medicina 2': 'iconos\medicina 2.png',
    'medicina': 'iconos\medicina.png',
    'medicopaciente': 'iconos\medicopaciente.png',
    'medicos': 'iconos\medicos.png',
    'pacientes': 'iconos\pacientes.png',
    'pediatria': 'iconos\pediatria.png',
    'SIMV': 'iconos\SIMV.png',
    'usuario': 'iconos\usuario.png',
}
